//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4927
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

namespace BeerXMLSupportLibrary
{

	// 
	// This source code was auto-generated by xsd, Version=2.0.50727.3038.
	// 


	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
	[System.SerializableAttribute()]
	//[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[XmlTypeAttribute(AnonymousType = true, Namespace = "urn:beerxml:v2")]
	[XmlRootAttribute(Namespace = "urn:beerxml:v2", IsNullable = false)]
	public partial class beer_xml
	{
		private decimal versionField;

		private object itemField;

		/// <remarks/>
		public decimal version
		{
			get
			{
				return this.versionField;
			}
			set
			{
				this.versionField = value;
			}
		}

		/// <remarks/>
		[XmlElementAttribute("cultures", typeof(beer_xmlCultures))]
		[XmlElementAttribute("fermentables", typeof(beer_xmlFermentables))]
		[XmlElementAttribute("hop_varieties", typeof(beer_xmlHop_varieties))]
		[XmlElementAttribute("miscellaneous_ingredients", typeof(beer_xmlMiscellaneous_ingredients))]
		[XmlElementAttribute("procedure", typeof(beer_xmlProcedure))]
		[XmlElementAttribute("profiles", typeof(beer_xmlProfiles))]
		[XmlElementAttribute("recipes", typeof(beer_xmlRecipes))]
		[XmlElementAttribute("styles", typeof(beer_xmlStyles))]
		public object Item
		{
			get
			{
				return this.itemField;
			}
			set
			{
				this.itemField = value;
			}
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[XmlTypeAttribute(AnonymousType = true, Namespace = "urn:beerxml:v2")]
	public partial class beer_xmlCultures
	{

		private CultureInformation[] yeastField;

		/// <remarks/>
		[XmlElementAttribute("yeast")]
		public CultureInformation[] yeast
		{
			get
			{
				return this.yeastField;
			}
			set
			{
				this.yeastField = value;
			}
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[XmlTypeAttribute(Namespace = "urn:beerxml:yeast:v2")]
	public partial class CultureInformation : CultureBase
	{

		private TemperatureRangeType temperature_rangeField;

		private QualitativeRangeType flocculationField;

		private bool flocculationFieldSpecified;

		private decimal attenuationField;

		private bool attenuationFieldSpecified;

		private PercentRangeType alcohol_toleranceField;

		private string notesField;

		private string best_forField;

		private string max_reuseField;

		private CultureInformationInventory inventoryField;

		/// <remarks/>
		public TemperatureRangeType temperature_range
		{
			get
			{
				return this.temperature_rangeField;
			}
			set
			{
				this.temperature_rangeField = value;
			}
		}

		/// <remarks/>
		public QualitativeRangeType flocculation
		{
			get
			{
				return this.flocculationField;
			}
			set
			{
				this.flocculationField = value;
			}
		}

		/// <remarks/>
		[XmlIgnoreAttribute()]
		public bool flocculationSpecified
		{
			get
			{
				return this.flocculationFieldSpecified;
			}
			set
			{
				this.flocculationFieldSpecified = value;
			}
		}

		/// <remarks/>
		public decimal attenuation
		{
			get
			{
				return this.attenuationField;
			}
			set
			{
				this.attenuationField = value;
			}
		}

		/// <remarks/>
		[XmlIgnoreAttribute()]
		public bool attenuationSpecified
		{
			get
			{
				return this.attenuationFieldSpecified;
			}
			set
			{
				this.attenuationFieldSpecified = value;
			}
		}

		/// <remarks/>
		public PercentRangeType alcohol_tolerance
		{
			get
			{
				return this.alcohol_toleranceField;
			}
			set
			{
				this.alcohol_toleranceField = value;
			}
		}

		/// <remarks/>
		public string notes
		{
			get
			{
				return this.notesField;
			}
			set
			{
				this.notesField = value;
			}
		}

		/// <remarks/>
		public string best_for
		{
			get
			{
				return this.best_forField;
			}
			set
			{
				this.best_forField = value;
			}
		}

		/// <remarks/>
		[XmlElementAttribute(DataType = "integer")]
		public string max_reuse
		{
			get
			{
				return this.max_reuseField;
			}
			set
			{
				this.max_reuseField = value;
			}
		}

		/// <remarks/>
		public CultureInformationInventory inventory
		{
			get
			{
				return this.inventoryField;
			}
			set
			{
				this.inventoryField = value;
			}
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[XmlTypeAttribute(Namespace = "urn:beerxml:unit:v2")]
	public partial class TemperatureRangeType
	{

		private TemperatureType minimumField;

		private TemperatureType maximumField;

		/// <remarks/>
		public TemperatureType minimum
		{
			get
			{
				return this.minimumField;
			}
			set
			{
				this.minimumField = value;
			}
		}

		/// <remarks/>
		public TemperatureType maximum
		{
			get
			{
				return this.maximumField;
			}
			set
			{
				this.maximumField = value;
			}
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[XmlTypeAttribute(Namespace = "urn:beerxml:unit:v2")]
	public partial class TemperatureType
	{

		private TemperatureUnitType degreesField;

		private decimal valueField;

		/// <remarks/>
		[XmlAttributeAttribute()]
		public TemperatureUnitType degrees
		{
			get
			{
				return this.degreesField;
			}
			set
			{
				this.degreesField = value;
			}
		}

		/// <remarks/>
		[XmlTextAttribute()]
		public decimal Value
		{
			get
			{
				return this.valueField;
			}
			set
			{
				this.valueField = value;
			}
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
	[System.SerializableAttribute()]
	[XmlTypeAttribute(Namespace = "urn:beerxml:unit:v2")]
	public enum TemperatureUnitType
	{

		/// <remarks/>
		C,

		/// <remarks/>
		F,
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[XmlTypeAttribute(Namespace = "urn:beerxml:recipe:v2")]
	public partial class FermentationStageType
	{

		private TimeType agingField;

		private TemperatureType temperatureField;

		/// <remarks/>
		public TimeType aging
		{
			get
			{
				return this.agingField;
			}
			set
			{
				this.agingField = value;
			}
		}

		/// <remarks/>
		public TemperatureType temperature
		{
			get
			{
				return this.temperatureField;
			}
			set
			{
				this.temperatureField = value;
			}
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[XmlTypeAttribute(Namespace = "urn:beerxml:unit:v2")]
	public partial class TimeType
	{

		private TimeUnitType durationField;

		private decimal valueField;

		/// <remarks/>
		[XmlAttributeAttribute()]
		public TimeUnitType duration
		{
			get
			{
				return this.durationField;
			}
			set
			{
				this.durationField = value;
			}
		}

		/// <remarks/>
		[XmlTextAttribute()]
		public decimal Value
		{
			get
			{
				return this.valueField;
			}
			set
			{
				this.valueField = value;
			}
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
	[System.SerializableAttribute()]
	[XmlTypeAttribute(Namespace = "urn:beerxml:unit:v2")]
	public enum TimeUnitType
	{

		/// <remarks/>
		sec,

		/// <remarks/>
		min,

		/// <remarks/>
		hr,

		/// <remarks/>
		day,

		/// <remarks/>
		week,

		/// <remarks/>
		month,

		/// <remarks/>
		year,
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[XmlTypeAttribute(Namespace = "urn:beerxml:hop:v2")]
	public partial class IBUEstimateType
	{

		private IBUMethodType methodField;

		private decimal valueField;

		/// <remarks/>
		[XmlAttributeAttribute()]
		public IBUMethodType method
		{
			get
			{
				return this.methodField;
			}
			set
			{
				this.methodField = value;
			}
		}

		/// <remarks/>
		[XmlTextAttribute()]
		public decimal Value
		{
			get
			{
				return this.valueField;
			}
			set
			{
				this.valueField = value;
			}
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
	[System.SerializableAttribute()]
	[XmlTypeAttribute(Namespace = "urn:beerxml:hop:v2")]
	public enum IBUMethodType
	{

		/// <remarks/>
		Rager,

		/// <remarks/>
		Tinseth,

		/// <remarks/>
		Garetz,

		/// <remarks/>
		Other,
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
	[System.SerializableAttribute()]
	//[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[XmlTypeAttribute(Namespace = "urn:beerxml:recipe:v2")]
	public partial class RecipeType
	{

		private string nameField;

		private RecipeTypeType typeField;

		private string authorField;

		private string coauthorField;

		private string createdField;

		private VolumeType batch_sizeField;

		private VolumeType boil_sizeField;

		private TimeType boil_timeField;

		private decimal efficiencyField;

		private bool efficiencyFieldSpecified;

		private RecipeStyleType styleField;

		private RecipeTypeIngredients ingredientsField;

		private MashProcedureType mashField;

		private string notesField;

		private DensityType original_gravityField;

		private DensityType final_gravityField;

		private decimal alcohol_by_volumeField;

		private bool alcohol_by_volumeFieldSpecified;

		private IBUEstimateType ibu_estimateField;

		private ColorType color_estimateField;

		private decimal carbonationField;

		private bool carbonationFieldSpecified;

		private RecipeTypeFermentation_stages fermentation_stagesField;

		private RecipeTypeTaste tasteField;

		private decimal calories_per_pintField;

		private bool calories_per_pintFieldSpecified;

	
		public string name
		{
			get
			{
				return this.nameField;
			}
			set
			{
				this.nameField = value;
			}
		}

		public RecipeTypeType type
		{
			get
			{
				return this.typeField;
			}
			set
			{
				this.typeField = value;
			}
		}

		public string author
		{
			get
			{
				return this.authorField;
			}
			set
			{
				this.authorField = value;
			}
		}

		public string coauthor
		{
			get
			{
				return this.coauthorField;
			}
			set
			{
				this.coauthorField = value;
			}
		}

		public string created
		{
			get
			{
				return this.createdField;
			}
			set
			{
				this.createdField = value;
			}
		}

		public VolumeType batch_size
		{
			get
			{
				return this.batch_sizeField;
			}
			set
			{
				this.batch_sizeField = value;
			}
		}

		public VolumeType boil_size
		{
			get
			{
				return this.boil_sizeField;
			}
			set
			{
				this.boil_sizeField = value;
			}
		}

		public TimeType boil_time
		{
			get
			{
				return this.boil_timeField;
			}
			set
			{
				this.boil_timeField = value;
			}
		}

		public decimal efficiency
		{
			get
			{
				return this.efficiencyField;
			}
			set
			{
				this.efficiencyField = value;
			}
		}

		[XmlIgnoreAttribute()]
		public bool efficiencySpecified
		{
			get
			{
				return this.efficiencyFieldSpecified;
			}
			set
			{
				this.efficiencyFieldSpecified = value;
			}
		}

		public RecipeStyleType style
		{
			get
			{
				return this.styleField;
			}
			set
			{
				this.styleField = value;
			}
		}

		public RecipeTypeIngredients ingredients
		{
			get
			{
				return this.ingredientsField;
			}
			set
			{
				this.ingredientsField = value;
			}
		}

		public MashProcedureType mash
		{
			get
			{
				return this.mashField;
			}
			set
			{
				this.mashField = value;
			}
		}

		public string notes
		{
			get
			{
				return this.notesField;
			}
			set
			{
				this.notesField = value;
			}
		}

		public DensityType original_gravity
		{
			get
			{
				return this.original_gravityField;
			}
			set
			{
				this.original_gravityField = value;
			}
		}

		public DensityType final_gravity
		{
			get
			{
				return this.final_gravityField;
			}
			set
			{
				this.final_gravityField = value;
			}
		}

		public decimal alcohol_by_volume
		{
			get
			{
				return this.alcohol_by_volumeField;
			}
			set
			{
				this.alcohol_by_volumeField = value;
			}
		}

		[XmlIgnoreAttribute()]
		public bool alcohol_by_volumeSpecified
		{
			get
			{
				return this.alcohol_by_volumeFieldSpecified;
			}
			set
			{
				this.alcohol_by_volumeFieldSpecified = value;
			}
		}

		public IBUEstimateType ibu_estimate
		{
			get
			{
				return this.ibu_estimateField;
			}
			set
			{
				this.ibu_estimateField = value;
			}
		}

		public ColorType color_estimate
		{
			get
			{
				return this.color_estimateField;
			}
			set
			{
				this.color_estimateField = value;
			}
		}

		public decimal carbonation
		{
			get
			{
				return this.carbonationField;
			}
			set
			{
				this.carbonationField = value;
			}
		}

		[XmlIgnoreAttribute()]
		public bool carbonationSpecified
		{
			get
			{
				return this.carbonationFieldSpecified;
			}
			set
			{
				this.carbonationFieldSpecified = value;
			}
		}

		public RecipeTypeFermentation_stages fermentation_stages
		{
			get
			{
				return this.fermentation_stagesField;
			}
			set
			{
				this.fermentation_stagesField = value;
			}
		}

		public RecipeTypeTaste taste
		{
			get
			{
				return this.tasteField;
			}
			set
			{
				this.tasteField = value;
			}
		}

		public decimal calories_per_pint
		{
			get
			{
				return this.calories_per_pintField;
			}
			set
			{
				this.calories_per_pintField = value;
			}
		}

		[XmlIgnoreAttribute()]
		public bool calories_per_pintSpecified
		{
			get
			{
				return this.calories_per_pintFieldSpecified;
			}
			set
			{
				this.calories_per_pintFieldSpecified = value;
			}
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
	[System.SerializableAttribute()]
	[XmlTypeAttribute(AnonymousType = true, Namespace = "urn:beerxml:recipe:v2")]
	public enum RecipeTypeType
	{

		/// <remarks/>
		extract,

		/// <remarks/>
		[XmlEnumAttribute("partial mash")]
		partialmash,

		/// <remarks/>
		[XmlEnumAttribute("all grain")]
		allgrain,
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[XmlTypeAttribute(Namespace = "urn:beerxml:unit:v2")]
	public partial class VolumeType
	{

		private VolumeUnitType volumeField;

		private decimal valueField;

		/// <remarks/>
		[XmlAttributeAttribute()]
		public VolumeUnitType volume
		{
			get
			{
				return this.volumeField;
			}
			set
			{
				this.volumeField = value;
			}
		}

		/// <remarks/>
		[XmlTextAttribute()]
		public decimal Value
		{
			get
			{
				return this.valueField;
			}
			set
			{
				this.valueField = value;
			}
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
	[System.SerializableAttribute()]
	[XmlTypeAttribute(Namespace = "urn:beerxml:unit:v2")]
	public enum VolumeUnitType
	{

		/// <remarks/>
		ml,

		/// <remarks/>
		l,

		/// <remarks/>
		tsp,

		/// <remarks/>
		tbsp,

		/// <remarks/>
		ozfl,

		/// <remarks/>
		cup,

		/// <remarks/>
		pt,

		/// <remarks/>
		qt,

		/// <remarks/>
		gal,

		/// <remarks/>
		bbl,

		/// <remarks/>
		iozfl,

		/// <remarks/>
		ipt,

		/// <remarks/>
		iqt,

		/// <remarks/>
		igal,

		/// <remarks/>
		ibbl,
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[XmlTypeAttribute(Namespace = "urn:beerxml:style:v2")]
	public partial class RecipeStyleType : StyleBase
	{
	}

	/// <remarks/>
	[XmlIncludeAttribute(typeof(RecipeStyleType))]
	[XmlIncludeAttribute(typeof(StyleType))]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[XmlTypeAttribute(Namespace = "urn:beerxml:style:v2")]
	public partial class StyleBase
	{

		private string nameField;

		private string categoryField;

		private string category_numberField;

		private string style_letterField;

		private string style_guideField;

		private StyleCategories typeField;


		public string name
		{
			get
			{
				return this.nameField;
			}
			set
			{
				this.nameField = value;
			}
		}

		public string category
		{
			get
			{
				return this.categoryField;
			}
			set
			{
				this.categoryField = value;
			}
		}

		[XmlElementAttribute(DataType = "integer")]
		public string category_number
		{
			get
			{
				return this.category_numberField;
			}
			set
			{
				this.category_numberField = value;
			}
		}

		public string style_letter
		{
			get
			{
				return this.style_letterField;
			}
			set
			{
				this.style_letterField = value;
			}
		}

		public string style_guide
		{
			get
			{
				return this.style_guideField;
			}
			set
			{
				this.style_guideField = value;
			}
		}

		public StyleCategories type
		{
			get
			{
				return this.typeField;
			}
			set
			{
				this.typeField = value;
			}
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
	[System.SerializableAttribute()]
	[XmlTypeAttribute(Namespace = "urn:beerxml:style:v2")]
	public enum StyleCategories
	{

		/// <remarks/>
		lager,

		/// <remarks/>
		ale,

		/// <remarks/>
		mead,

		/// <remarks/>
		wheat,

		/// <remarks/>
		mixed,

		/// <remarks/>
		cider,
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[XmlTypeAttribute(Namespace = "urn:beerxml:style:v2")]
	public partial class StyleType : StyleBase
	{

		private DensityRangeType original_gravityField;

		private DensityRangeType final_gravityField;

		private QuantitativeRangeType international_bitterness_unitsField;

		private ColorRangeType colorField;

		private QuantitativeRangeType carbonationField;

		private PercentRangeType alcohol_by_volumeField;

		private string notesField;

		private string profileField;

		private string ingredientsField;

		private string examplesField;

		/// <remarks/>
		public DensityRangeType original_gravity
		{
			get
			{
				return this.original_gravityField;
			}
			set
			{
				this.original_gravityField = value;
			}
		}

		/// <remarks/>
		public DensityRangeType final_gravity
		{
			get
			{
				return this.final_gravityField;
			}
			set
			{
				this.final_gravityField = value;
			}
		}

		/// <remarks/>
		public QuantitativeRangeType international_bitterness_units
		{
			get
			{
				return this.international_bitterness_unitsField;
			}
			set
			{
				this.international_bitterness_unitsField = value;
			}
		}

		/// <remarks/>
		public ColorRangeType color
		{
			get
			{
				return this.colorField;
			}
			set
			{
				this.colorField = value;
			}
		}

		/// <remarks/>
		public QuantitativeRangeType carbonation
		{
			get
			{
				return this.carbonationField;
			}
			set
			{
				this.carbonationField = value;
			}
		}

		/// <remarks/>
		public PercentRangeType alcohol_by_volume
		{
			get
			{
				return this.alcohol_by_volumeField;
			}
			set
			{
				this.alcohol_by_volumeField = value;
			}
		}

		/// <remarks/>
		public string notes
		{
			get
			{
				return this.notesField;
			}
			set
			{
				this.notesField = value;
			}
		}

		/// <remarks/>
		public string profile
		{
			get
			{
				return this.profileField;
			}
			set
			{
				this.profileField = value;
			}
		}

		/// <remarks/>
		public string ingredients
		{
			get
			{
				return this.ingredientsField;
			}
			set
			{
				this.ingredientsField = value;
			}
		}

		/// <remarks/>
		public string examples
		{
			get
			{
				return this.examplesField;
			}
			set
			{
				this.examplesField = value;
			}
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[XmlTypeAttribute(Namespace = "urn:beerxml:unit:v2")]
	public partial class DensityRangeType
	{

		private DensityType minimumField;

		private DensityType maximumField;

		/// <remarks/>
		public DensityType minimum
		{
			get
			{
				return this.minimumField;
			}
			set
			{
				this.minimumField = value;
			}
		}

		/// <remarks/>
		public DensityType maximum
		{
			get
			{
				return this.maximumField;
			}
			set
			{
				this.maximumField = value;
			}
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[XmlTypeAttribute(Namespace = "urn:beerxml:unit:v2")]
	public partial class DensityType
	{

		private DensityUnitType densityField;

		private decimal valueField;

		/// <remarks/>
		[XmlAttributeAttribute()]
		public DensityUnitType density
		{
			get
			{
				return this.densityField;
			}
			set
			{
				this.densityField = value;
			}
		}

		/// <remarks/>
		[XmlTextAttribute()]
		public decimal Value
		{
			get
			{
				return this.valueField;
			}
			set
			{
				this.valueField = value;
			}
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
	[System.SerializableAttribute()]
	[XmlTypeAttribute(Namespace = "urn:beerxml:unit:v2")]
	public enum DensityUnitType
	{

		/// <remarks/>
		sg,

		/// <remarks/>
		plato,
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[XmlTypeAttribute(Namespace = "urn:beerxml:unit:v2")]
	public partial class QuantitativeRangeType
	{

		private decimal minimumField;

		private decimal maximumField;

		/// <remarks/>
		public decimal minimum
		{
			get
			{
				return this.minimumField;
			}
			set
			{
				this.minimumField = value;
			}
		}

		/// <remarks/>
		public decimal maximum
		{
			get
			{
				return this.maximumField;
			}
			set
			{
				this.maximumField = value;
			}
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[XmlTypeAttribute(Namespace = "urn:beerxml:unit:v2")]
	public partial class ColorRangeType
	{

		private ColorType minimumField;

		private ColorType maximumField;

		/// <remarks/>
		public ColorType minimum
		{
			get
			{
				return this.minimumField;
			}
			set
			{
				this.minimumField = value;
			}
		}

		/// <remarks/>
		public ColorType maximum
		{
			get
			{
				return this.maximumField;
			}
			set
			{
				this.maximumField = value;
			}
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[XmlTypeAttribute(Namespace = "urn:beerxml:unit:v2")]
	public partial class ColorType
	{

		private ColorUnitType scaleField;

		private decimal valueField;

		/// <remarks/>
		[XmlAttributeAttribute()]
		public ColorUnitType scale
		{
			get
			{
				return this.scaleField;
			}
			set
			{
				this.scaleField = value;
			}
		}

		/// <remarks/>
		[XmlTextAttribute()]
		public decimal Value
		{
			get
			{
				return this.valueField;
			}
			set
			{
				this.valueField = value;
			}
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
	[System.SerializableAttribute()]
	[XmlTypeAttribute(Namespace = "urn:beerxml:unit:v2")]
	public enum ColorUnitType
	{

		/// <remarks/>
		EBC,

		/// <remarks/>
		L,

		/// <remarks/>
		SRM,
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[XmlTypeAttribute(Namespace = "urn:beerxml:unit:v2")]
	public partial class PercentRangeType
	{

		private decimal minimumField;

		private decimal maximumField;

		/// <remarks/>
		public decimal minimum
		{
			get
			{
				return this.minimumField;
			}
			set
			{
				this.minimumField = value;
			}
		}

		/// <remarks/>
		public decimal maximum
		{
			get
			{
				return this.maximumField;
			}
			set
			{
				this.maximumField = value;
			}
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[XmlTypeAttribute(AnonymousType = true, Namespace = "urn:beerxml:recipe:v2")]
	public partial class RecipeTypeIngredients
	{

		private FermentableAdditionTypeAddition[] grain_billField;

		private HopAdditionTypeAddition[] hop_billField;

		private MiscellaneousAdditionTypeAddition[] adjunctsField;

		private YeastAdditionTypeAddition[] yeast_additionsField;

		private WaterAdditionTypeAddition[] water_profileField;

		/// <remarks/>
		[XmlArrayItemAttribute("addition", Namespace = "urn:beerxml:fermentable:v2", IsNullable = false)]
		public FermentableAdditionTypeAddition[] grain_bill
		{
			get
			{
				return this.grain_billField;
			}
			set
			{
				this.grain_billField = value;
			}
		}

		/// <remarks/>
		[XmlArrayItemAttribute("addition", Namespace = "urn:beerxml:hop:v2", IsNullable = false)]
		public HopAdditionTypeAddition[] hop_bill
		{
			get
			{
				return this.hop_billField;
			}
			set
			{
				this.hop_billField = value;
			}
		}

		/// <remarks/>
		[XmlArrayItemAttribute("addition", Namespace = "urn:beerxml:miscellaneous:v2", IsNullable = false)]
		public MiscellaneousAdditionTypeAddition[] adjuncts
		{
			get
			{
				return this.adjunctsField;
			}
			set
			{
				this.adjunctsField = value;
			}
		}

		/// <remarks/>
		[XmlArrayItemAttribute("addition", Namespace = "urn:beerxml:yeast:v2", IsNullable = false)]
		public YeastAdditionTypeAddition[] yeast_additions
		{
			get
			{
				return this.yeast_additionsField;
			}
			set
			{
				this.yeast_additionsField = value;
			}
		}

		/// <remarks/>
		[XmlArrayItemAttribute("addition", Namespace = "urn:beerxml:water:v2", IsNullable = false)]
		public WaterAdditionTypeAddition[] water_profile
		{
			get
			{
				return this.water_profileField;
			}
			set
			{
				this.water_profileField = value;
			}
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[XmlTypeAttribute(AnonymousType = true, Namespace = "urn:beerxml:fermentable:v2")]
	public partial class FermentableAdditionTypeAddition : FermentableBase
	{

		private MassType amountField;

		private bool add_after_boilField;

		private bool add_after_boilFieldSpecified;


		public MassType amount
		{
			get
			{
				return this.amountField;
			}
			set
			{
				this.amountField = value;
			}
		}

		public bool add_after_boil
		{
			get
			{
				return this.add_after_boilField;
			}
			set
			{
				this.add_after_boilField = value;
			}
		}

		[XmlIgnoreAttribute()]
		public bool add_after_boilSpecified
		{
			get
			{
				return this.add_after_boilFieldSpecified;
			}
			set
			{
				this.add_after_boilFieldSpecified = value;
			}
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[XmlTypeAttribute(Namespace = "urn:beerxml:unit:v2")]
	public partial class MassType
	{

		private MassUnitType massField;

		private decimal valueField;

		/// <remarks/>
		[XmlAttributeAttribute()]
		public MassUnitType mass
		{
			get
			{
				return this.massField;
			}
			set
			{
				this.massField = value;
			}
		}

		/// <remarks/>
		[XmlTextAttribute()]
		public decimal Value
		{
			get
			{
				return this.valueField;
			}
			set
			{
				this.valueField = value;
			}
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
	[System.SerializableAttribute()]
	[XmlTypeAttribute(Namespace = "urn:beerxml:unit:v2")]
	public enum MassUnitType
	{

		/// <remarks/>
		mg,

		/// <remarks/>
		g,

		/// <remarks/>
		kg,

		/// <remarks/>
		lb,

		/// <remarks/>
		oz,
	}

	/// <remarks/>
	[XmlIncludeAttribute(typeof(FermentableType))]
	[XmlIncludeAttribute(typeof(GrainType))]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[XmlTypeAttribute(Namespace = "urn:beerxml:fermentable:v2")]
	public partial class FermentableBase
	{

		private string nameField;

		private FermentableBaseType typeField;

		private ColorType colorField;

		private string originField;

		private string supplierField;


		public string name
		{
			get
			{
				return this.nameField;
			}
			set
			{
				this.nameField = value;
			}
		}

		public FermentableBaseType type
		{
			get
			{
				return this.typeField;
			}
			set
			{
				this.typeField = value;
			}
		}

		public ColorType color
		{
			get
			{
				return this.colorField;
			}
			set
			{
				this.colorField = value;
			}
		}

		public string origin
		{
			get
			{
				return this.originField;
			}
			set
			{
				this.originField = value;
			}
		}

		public string supplier
		{
			get
			{
				return this.supplierField;
			}
			set
			{
				this.supplierField = value;
			}
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
	[System.SerializableAttribute()]
	[XmlTypeAttribute(AnonymousType = true, Namespace = "urn:beerxml:fermentable:v2")]
	public enum FermentableBaseType
	{

		/// <remarks/>
		adjunct,

		/// <remarks/>
		[XmlEnumAttribute("dry extract")]
		dryextract,

		/// <remarks/>
		extract,

		/// <remarks/>
		grain,

		/// <remarks/>
		sugar,
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[XmlTypeAttribute(Namespace = "urn:beerxml:fermentable:v2")]
	public partial class FermentableType : FermentableBase
	{

		private string notesField;

		private decimal max_in_batchField;

		private bool max_in_batchFieldSpecified;

		private decimal ibu_gal_per_lbField;

		private bool ibu_gal_per_lbFieldSpecified;

		private DensityType potentialField;

		private FermentableTypeInventory inventoryField;

		/// <remarks/>
		public string notes
		{
			get
			{
				return this.notesField;
			}
			set
			{
				this.notesField = value;
			}
		}

		/// <remarks/>
		public decimal max_in_batch
		{
			get
			{
				return this.max_in_batchField;
			}
			set
			{
				this.max_in_batchField = value;
			}
		}

		/// <remarks/>
		[XmlIgnoreAttribute()]
		public bool max_in_batchSpecified
		{
			get
			{
				return this.max_in_batchFieldSpecified;
			}
			set
			{
				this.max_in_batchFieldSpecified = value;
			}
		}

		/// <remarks/>
		public decimal ibu_gal_per_lb
		{
			get
			{
				return this.ibu_gal_per_lbField;
			}
			set
			{
				this.ibu_gal_per_lbField = value;
			}
		}

		/// <remarks/>
		[XmlIgnoreAttribute()]
		public bool ibu_gal_per_lbSpecified
		{
			get
			{
				return this.ibu_gal_per_lbFieldSpecified;
			}
			set
			{
				this.ibu_gal_per_lbFieldSpecified = value;
			}
		}

		/// <remarks/>
		public DensityType potential
		{
			get
			{
				return this.potentialField;
			}
			set
			{
				this.potentialField = value;
			}
		}

		/// <remarks/>
		public FermentableTypeInventory inventory
		{
			get
			{
				return this.inventoryField;
			}
			set
			{
				this.inventoryField = value;
			}
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[XmlTypeAttribute(AnonymousType = true, Namespace = "urn:beerxml:fermentable:v2")]
	public partial class FermentableTypeInventory
	{

		private object itemField;

		/// <remarks/>
		[XmlElementAttribute("amount", typeof(VolumeType))]
		[XmlElementAttribute("amount_as_weight", typeof(MassType))]
		public object Item
		{
			get
			{
				return this.itemField;
			}
			set
			{
				this.itemField = value;
			}
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[XmlTypeAttribute(Namespace = "urn:beerxml:fermentable:v2")]
	public partial class GrainType : FermentableBase
	{

		private GrainTypeYield_dry_basis yield_dry_basisField;

		private string notesField;

		private decimal moistureField;

		private bool moistureFieldSpecified;

		private decimal diastatic_powerField;

		private bool diastatic_powerFieldSpecified;

		private decimal proteinField;

		private bool proteinFieldSpecified;

		private decimal soluble_nitrogen_ratioField;

		private bool soluble_nitrogen_ratioFieldSpecified;

		private decimal max_in_batchField;

		private bool max_in_batchFieldSpecified;

		private bool recommend_mashField;

		private bool recommend_mashFieldSpecified;

		private DensityType potentialField;

		private MassType inventoryField;

		/// <remarks/>
		public GrainTypeYield_dry_basis yield_dry_basis
		{
			get
			{
				return this.yield_dry_basisField;
			}
			set
			{
				this.yield_dry_basisField = value;
			}
		}

		/// <remarks/>
		public string notes
		{
			get
			{
				return this.notesField;
			}
			set
			{
				this.notesField = value;
			}
		}

		/// <remarks/>
		public decimal moisture
		{
			get
			{
				return this.moistureField;
			}
			set
			{
				this.moistureField = value;
			}
		}

		/// <remarks/>
		[XmlIgnoreAttribute()]
		public bool moistureSpecified
		{
			get
			{
				return this.moistureFieldSpecified;
			}
			set
			{
				this.moistureFieldSpecified = value;
			}
		}

		/// <remarks/>
		public decimal diastatic_power
		{
			get
			{
				return this.diastatic_powerField;
			}
			set
			{
				this.diastatic_powerField = value;
			}
		}

		/// <remarks/>
		[XmlIgnoreAttribute()]
		public bool diastatic_powerSpecified
		{
			get
			{
				return this.diastatic_powerFieldSpecified;
			}
			set
			{
				this.diastatic_powerFieldSpecified = value;
			}
		}

		/// <remarks/>
		public decimal protein
		{
			get
			{
				return this.proteinField;
			}
			set
			{
				this.proteinField = value;
			}
		}

		/// <remarks/>
		[XmlIgnoreAttribute()]
		public bool proteinSpecified
		{
			get
			{
				return this.proteinFieldSpecified;
			}
			set
			{
				this.proteinFieldSpecified = value;
			}
		}

		/// <remarks/>
		public decimal soluble_nitrogen_ratio
		{
			get
			{
				return this.soluble_nitrogen_ratioField;
			}
			set
			{
				this.soluble_nitrogen_ratioField = value;
			}
		}

		/// <remarks/>
		[XmlIgnoreAttribute()]
		public bool soluble_nitrogen_ratioSpecified
		{
			get
			{
				return this.soluble_nitrogen_ratioFieldSpecified;
			}
			set
			{
				this.soluble_nitrogen_ratioFieldSpecified = value;
			}
		}

		/// <remarks/>
		public decimal max_in_batch
		{
			get
			{
				return this.max_in_batchField;
			}
			set
			{
				this.max_in_batchField = value;
			}
		}

		/// <remarks/>
		[XmlIgnoreAttribute()]
		public bool max_in_batchSpecified
		{
			get
			{
				return this.max_in_batchFieldSpecified;
			}
			set
			{
				this.max_in_batchFieldSpecified = value;
			}
		}

		/// <remarks/>
		public bool recommend_mash
		{
			get
			{
				return this.recommend_mashField;
			}
			set
			{
				this.recommend_mashField = value;
			}
		}

		/// <remarks/>
		[XmlIgnoreAttribute()]
		public bool recommend_mashSpecified
		{
			get
			{
				return this.recommend_mashFieldSpecified;
			}
			set
			{
				this.recommend_mashFieldSpecified = value;
			}
		}

		/// <remarks/>
		public DensityType potential
		{
			get
			{
				return this.potentialField;
			}
			set
			{
				this.potentialField = value;
			}
		}

		/// <remarks/>
		public MassType inventory
		{
			get
			{
				return this.inventoryField;
			}
			set
			{
				this.inventoryField = value;
			}
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[XmlTypeAttribute(AnonymousType = true, Namespace = "urn:beerxml:fermentable:v2")]
	public partial class GrainTypeYield_dry_basis
	{

		private decimal fine_grindField;

		private decimal coarse_grindField;

		private bool coarse_grindFieldSpecified;

		private decimal fine_coarse_differenceField;

		private bool fine_coarse_differenceFieldSpecified;

		/// <remarks/>
		public decimal fine_grind
		{
			get
			{
				return this.fine_grindField;
			}
			set
			{
				this.fine_grindField = value;
			}
		}

		/// <remarks/>
		public decimal coarse_grind
		{
			get
			{
				return this.coarse_grindField;
			}
			set
			{
				this.coarse_grindField = value;
			}
		}

		/// <remarks/>
		[XmlIgnoreAttribute()]
		public bool coarse_grindSpecified
		{
			get
			{
				return this.coarse_grindFieldSpecified;
			}
			set
			{
				this.coarse_grindFieldSpecified = value;
			}
		}

		/// <remarks/>
		public decimal fine_coarse_difference
		{
			get
			{
				return this.fine_coarse_differenceField;
			}
			set
			{
				this.fine_coarse_differenceField = value;
			}
		}

		/// <remarks/>
		[XmlIgnoreAttribute()]
		public bool fine_coarse_differenceSpecified
		{
			get
			{
				return this.fine_coarse_differenceFieldSpecified;
			}
			set
			{
				this.fine_coarse_differenceFieldSpecified = value;
			}
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[XmlTypeAttribute(AnonymousType = true, Namespace = "urn:beerxml:hop:v2")]
	public partial class HopAdditionTypeAddition : HopVarietyBase
	{

		private HopAdditionTypeAdditionForm formField;

		private HopAdditionTypeAdditionUse useField;

		private MassType amountField;

		private TimeType timeField;


		public HopAdditionTypeAdditionForm form
		{
			get
			{
				return this.formField;
			}
			set
			{
				this.formField = value;
			}
		}

		public HopAdditionTypeAdditionUse use
		{
			get
			{
				return this.useField;
			}
			set
			{
				this.useField = value;
			}
		}

		public MassType amount
		{
			get
			{
				return this.amountField;
			}
			set
			{
				this.amountField = value;
			}
		}

		public TimeType time
		{
			get
			{
				return this.timeField;
			}
			set
			{
				this.timeField = value;
			}
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
	[System.SerializableAttribute()]
	[XmlTypeAttribute(AnonymousType = true, Namespace = "urn:beerxml:hop:v2")]
	public enum HopAdditionTypeAdditionForm
	{

		/// <remarks/>
		leaf,

		/// <remarks/>
		pellet,

		/// <remarks/>
		plug,
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
	[System.SerializableAttribute()]
	[XmlTypeAttribute(AnonymousType = true, Namespace = "urn:beerxml:hop:v2")]
	public enum HopAdditionTypeAdditionUse
	{

		/// <remarks/>
		boil,

		/// <remarks/>
		[XmlEnumAttribute("dry hop")]
		dryhop,

		/// <remarks/>
		[XmlEnumAttribute("first wort")]
		firstwort,

		/// <remarks/>
		hopback,

		/// <remarks/>
		mash,

		/// <remarks/>
		[XmlEnumAttribute("continuous boil addition")]
		continuousboiladdition,
	}

	/// <remarks/>
	[XmlIncludeAttribute(typeof(VarietyInformation))]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[XmlTypeAttribute(Namespace = "urn:beerxml:hop:v2")]
	public partial class HopVarietyBase
	{

		private string nameField;

		private string originField;

		private decimal alpha_acid_unitsField;

		private decimal beta_acid_unitsField;

		private bool beta_acid_unitsFieldSpecified;


		public string name
		{
			get
			{
				return this.nameField;
			}
			set
			{
				this.nameField = value;
			}
		}

		public string origin
		{
			get
			{
				return this.originField;
			}
			set
			{
				this.originField = value;
			}
		}

		public decimal alpha_acid_units
		{
			get
			{
				return this.alpha_acid_unitsField;
			}
			set
			{
				this.alpha_acid_unitsField = value;
			}
		}

		public decimal beta_acid_units
		{
			get
			{
				return this.beta_acid_unitsField;
			}
			set
			{
				this.beta_acid_unitsField = value;
			}
		}

		[XmlIgnoreAttribute()]
		public bool beta_acid_unitsSpecified
		{
			get
			{
				return this.beta_acid_unitsFieldSpecified;
			}
			set
			{
				this.beta_acid_unitsFieldSpecified = value;
			}
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[XmlTypeAttribute(Namespace = "urn:beerxml:hop:v2")]
	public partial class VarietyInformation : HopVarietyBase
	{

		private VarietyInformationType typeField;

		private bool typeFieldSpecified;

		private string notesField;

		private decimal percent_lostField;

		private bool percent_lostFieldSpecified;

		private string substitutesField;

		private decimal humuleneField;

		private bool humuleneFieldSpecified;

		private decimal caryophylleneField;

		private bool caryophylleneFieldSpecified;

		private decimal cohumuloneField;

		private bool cohumuloneFieldSpecified;

		private decimal myrceneField;

		private bool myrceneFieldSpecified;

		private decimal farneseneField;

		private bool farneseneFieldSpecified;

		private VarietyInformationInventory inventoryField;

		/// <remarks/>
		public VarietyInformationType type
		{
			get
			{
				return this.typeField;
			}
			set
			{
				this.typeField = value;
			}
		}

		/// <remarks/>
		[XmlIgnoreAttribute()]
		public bool typeSpecified
		{
			get
			{
				return this.typeFieldSpecified;
			}
			set
			{
				this.typeFieldSpecified = value;
			}
		}

		/// <remarks/>
		public string notes
		{
			get
			{
				return this.notesField;
			}
			set
			{
				this.notesField = value;
			}
		}

		/// <remarks/>
		public decimal percent_lost
		{
			get
			{
				return this.percent_lostField;
			}
			set
			{
				this.percent_lostField = value;
			}
		}

		/// <remarks/>
		[XmlIgnoreAttribute()]
		public bool percent_lostSpecified
		{
			get
			{
				return this.percent_lostFieldSpecified;
			}
			set
			{
				this.percent_lostFieldSpecified = value;
			}
		}

		/// <remarks/>
		public string substitutes
		{
			get
			{
				return this.substitutesField;
			}
			set
			{
				this.substitutesField = value;
			}
		}

		/// <remarks/>
		public decimal humulene
		{
			get
			{
				return this.humuleneField;
			}
			set
			{
				this.humuleneField = value;
			}
		}

		/// <remarks/>
		[XmlIgnoreAttribute()]
		public bool humuleneSpecified
		{
			get
			{
				return this.humuleneFieldSpecified;
			}
			set
			{
				this.humuleneFieldSpecified = value;
			}
		}

		/// <remarks/>
		public decimal caryophyllene
		{
			get
			{
				return this.caryophylleneField;
			}
			set
			{
				this.caryophylleneField = value;
			}
		}

		/// <remarks/>
		[XmlIgnoreAttribute()]
		public bool caryophylleneSpecified
		{
			get
			{
				return this.caryophylleneFieldSpecified;
			}
			set
			{
				this.caryophylleneFieldSpecified = value;
			}
		}

		/// <remarks/>
		public decimal cohumulone
		{
			get
			{
				return this.cohumuloneField;
			}
			set
			{
				this.cohumuloneField = value;
			}
		}

		/// <remarks/>
		[XmlIgnoreAttribute()]
		public bool cohumuloneSpecified
		{
			get
			{
				return this.cohumuloneFieldSpecified;
			}
			set
			{
				this.cohumuloneFieldSpecified = value;
			}
		}

		/// <remarks/>
		public decimal myrcene
		{
			get
			{
				return this.myrceneField;
			}
			set
			{
				this.myrceneField = value;
			}
		}

		/// <remarks/>
		[XmlIgnoreAttribute()]
		public bool myrceneSpecified
		{
			get
			{
				return this.myrceneFieldSpecified;
			}
			set
			{
				this.myrceneFieldSpecified = value;
			}
		}

		/// <remarks/>
		public decimal farnesene
		{
			get
			{
				return this.farneseneField;
			}
			set
			{
				this.farneseneField = value;
			}
		}

		/// <remarks/>
		[XmlIgnoreAttribute()]
		public bool farneseneSpecified
		{
			get
			{
				return this.farneseneFieldSpecified;
			}
			set
			{
				this.farneseneFieldSpecified = value;
			}
		}

		/// <remarks/>
		public VarietyInformationInventory inventory
		{
			get
			{
				return this.inventoryField;
			}
			set
			{
				this.inventoryField = value;
			}
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
	[System.SerializableAttribute()]
	[XmlTypeAttribute(AnonymousType = true, Namespace = "urn:beerxml:hop:v2")]
	public enum VarietyInformationType
	{

		/// <remarks/>
		aroma,

		/// <remarks/>
		bittering,

		/// <remarks/>
		flavor,

		/// <remarks/>
		[XmlEnumAttribute("aroma/bittering")]
		aromabittering,

		/// <remarks/>
		[XmlEnumAttribute("bittering/flavor")]
		bitteringflavor,

		/// <remarks/>
		[XmlEnumAttribute("aroma/flavor")]
		aromaflavor,

		/// <remarks/>
		[XmlEnumAttribute("aroma/bittering/flavor")]
		aromabitteringflavor,
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[XmlTypeAttribute(AnonymousType = true, Namespace = "urn:beerxml:hop:v2")]
	public partial class VarietyInformationInventory
	{

		private MassType leafField;

		private MassType pelletField;

		private MassType plugField;

		/// <remarks/>
		public MassType leaf
		{
			get
			{
				return this.leafField;
			}
			set
			{
				this.leafField = value;
			}
		}

		/// <remarks/>
		public MassType pellet
		{
			get
			{
				return this.pelletField;
			}
			set
			{
				this.pelletField = value;
			}
		}

		/// <remarks/>
		public MassType plug
		{
			get
			{
				return this.plugField;
			}
			set
			{
				this.plugField = value;
			}
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[XmlTypeAttribute(AnonymousType = true, Namespace = "urn:beerxml:miscellaneous:v2")]
	public partial class MiscellaneousAdditionTypeAddition : MiscellaneousBase
	{

		private object itemField;

		private TimeType timeField;

		/// <remarks/>
		[XmlElementAttribute("amount", typeof(VolumeType))]
		[XmlElementAttribute("amount_as_weight", typeof(MassType))]
		public object Item
		{
			get
			{
				return this.itemField;
			}
			set
			{
				this.itemField = value;
			}
		}

		/// <remarks/>
		public TimeType time
		{
			get
			{
				return this.timeField;
			}
			set
			{
				this.timeField = value;
			}
		}
	}

	/// <remarks/>
	[XmlIncludeAttribute(typeof(MiscellaneousType))]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[XmlTypeAttribute(Namespace = "urn:beerxml:miscellaneous:v2")]
	public partial class MiscellaneousBase
	{

		private string nameField;

		private MiscellaneousBaseType typeField;

		private MiscellaneousBaseUse useField;


		public string name
		{
			get
			{
				return this.nameField;
			}
			set
			{
				this.nameField = value;
			}
		}

		public MiscellaneousBaseType type
		{
			get
			{
				return this.typeField;
			}
			set
			{
				this.typeField = value;
			}
		}

		public MiscellaneousBaseUse use
		{
			get
			{
				return this.useField;
			}
			set
			{
				this.useField = value;
			}
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
	[System.SerializableAttribute()]
	[XmlTypeAttribute(AnonymousType = true, Namespace = "urn:beerxml:miscellaneous:v2")]
	public enum MiscellaneousBaseType
	{

		/// <remarks/>
		spice,

		/// <remarks/>
		fining,

		/// <remarks/>
		[XmlEnumAttribute("water agent")]
		wateragent,

		/// <remarks/>
		herb,

		/// <remarks/>
		fruit,

		/// <remarks/>
		flavor,

		/// <remarks/>
		other,
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
	[System.SerializableAttribute()]
	[XmlTypeAttribute(AnonymousType = true, Namespace = "urn:beerxml:miscellaneous:v2")]
	public enum MiscellaneousBaseUse
	{

		/// <remarks/>
		boil,

		/// <remarks/>
		mash,

		/// <remarks/>
		primary,

		/// <remarks/>
		secondary,

		/// <remarks/>
		bottling,
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[XmlTypeAttribute(Namespace = "urn:beerxml:miscellaneous:v2")]
	public partial class MiscellaneousType : MiscellaneousBase
	{

		private string use_forField;

		private string notesField;

		private MiscellaneousTypeInventory inventoryField;

		/// <remarks/>
		public string use_for
		{
			get
			{
				return this.use_forField;
			}
			set
			{
				this.use_forField = value;
			}
		}

		/// <remarks/>
		public string notes
		{
			get
			{
				return this.notesField;
			}
			set
			{
				this.notesField = value;
			}
		}

		/// <remarks/>
		public MiscellaneousTypeInventory inventory
		{
			get
			{
				return this.inventoryField;
			}
			set
			{
				this.inventoryField = value;
			}
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[XmlTypeAttribute(AnonymousType = true, Namespace = "urn:beerxml:miscellaneous:v2")]
	public partial class MiscellaneousTypeInventory
	{

		private object itemField;

		/// <remarks/>
		[XmlElementAttribute("amount", typeof(VolumeType))]
		[XmlElementAttribute("amount_as_weight", typeof(MassType))]
		public object Item
		{
			get
			{
				return this.itemField;
			}
			set
			{
				this.itemField = value;
			}
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[XmlTypeAttribute(AnonymousType = true, Namespace = "urn:beerxml:yeast:v2")]
	public partial class YeastAdditionTypeAddition : CultureBase
	{

		private object itemField;

		private string times_culturedField;

		private bool add_to_secondaryField;

		private bool add_to_secondaryFieldSpecified;

		/// <remarks/>
		[XmlElementAttribute("amount", typeof(VolumeType))]
		[XmlElementAttribute("amount_as_weight", typeof(MassType))]
		public object Item
		{
			get
			{
				return this.itemField;
			}
			set
			{
				this.itemField = value;
			}
		}

		/// <remarks/>
		[XmlElementAttribute(DataType = "integer")]
		public string times_cultured
		{
			get
			{
				return this.times_culturedField;
			}
			set
			{
				this.times_culturedField = value;
			}
		}

		/// <remarks/>
		public bool add_to_secondary
		{
			get
			{
				return this.add_to_secondaryField;
			}
			set
			{
				this.add_to_secondaryField = value;
			}
		}

		/// <remarks/>
		[XmlIgnoreAttribute()]
		public bool add_to_secondarySpecified
		{
			get
			{
				return this.add_to_secondaryFieldSpecified;
			}
			set
			{
				this.add_to_secondaryFieldSpecified = value;
			}
		}
	}

	/// <remarks/>
	[XmlIncludeAttribute(typeof(CultureInformation))]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[XmlTypeAttribute(Namespace = "urn:beerxml:yeast:v2")]
	public partial class CultureBase
	{

		private string nameField;

		private CultureBaseType typeField;

		private CultureBaseForm formField;

		private string laboratoryField;

		private string product_idField;

		/// <remarks/>
		public string name
		{
			get
			{
				return this.nameField;
			}
			set
			{
				this.nameField = value;
			}
		}

		/// <remarks/>
		public CultureBaseType type
		{
			get
			{
				return this.typeField;
			}
			set
			{
				this.typeField = value;
			}
		}

		/// <remarks/>
		public CultureBaseForm form
		{
			get
			{
				return this.formField;
			}
			set
			{
				this.formField = value;
			}
		}

		/// <remarks/>
		public string laboratory
		{
			get
			{
				return this.laboratoryField;
			}
			set
			{
				this.laboratoryField = value;
			}
		}

		/// <remarks/>
		public string product_id
		{
			get
			{
				return this.product_idField;
			}
			set
			{
				this.product_idField = value;
			}
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
	[System.SerializableAttribute()]
	[XmlTypeAttribute(AnonymousType = true, Namespace = "urn:beerxml:yeast:v2")]
	public enum CultureBaseType
	{

		/// <remarks/>
		ale,

		/// <remarks/>
		lager,

		/// <remarks/>
		wheat,

		/// <remarks/>
		wine,

		/// <remarks/>
		champagne,
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
	[System.SerializableAttribute()]
	[XmlTypeAttribute(AnonymousType = true, Namespace = "urn:beerxml:yeast:v2")]
	public enum CultureBaseForm
	{

		/// <remarks/>
		liquid,

		/// <remarks/>
		dry,

		/// <remarks/>
		slant,

		/// <remarks/>
		culture,
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[XmlTypeAttribute(AnonymousType = true, Namespace = "urn:beerxml:water:v2")]
	public partial class WaterAdditionTypeAddition : WaterBase
	{

		private VolumeType amountField;

		/// <remarks/>
		public VolumeType amount
		{
			get
			{
				return this.amountField;
			}
			set
			{
				this.amountField = value;
			}
		}
	}

	/// <remarks/>
	[XmlIncludeAttribute(typeof(WaterType))]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[XmlTypeAttribute(Namespace = "urn:beerxml:water:v2")]
	public partial class WaterBase
	{

		private string nameField;

		private decimal calciumField;

		private decimal bicarbonateField;

		private decimal sulfateField;

		private decimal chlorideField;

		private decimal sodiumField;

		private decimal magnesiumField;

		/// <remarks/>
		public string name
		{
			get
			{
				return this.nameField;
			}
			set
			{
				this.nameField = value;
			}
		}

		/// <remarks/>
		public decimal calcium
		{
			get
			{
				return this.calciumField;
			}
			set
			{
				this.calciumField = value;
			}
		}

		/// <remarks/>
		public decimal bicarbonate
		{
			get
			{
				return this.bicarbonateField;
			}
			set
			{
				this.bicarbonateField = value;
			}
		}

		/// <remarks/>
		public decimal sulfate
		{
			get
			{
				return this.sulfateField;
			}
			set
			{
				this.sulfateField = value;
			}
		}

		/// <remarks/>
		public decimal chloride
		{
			get
			{
				return this.chlorideField;
			}
			set
			{
				this.chlorideField = value;
			}
		}

		/// <remarks/>
		public decimal sodium
		{
			get
			{
				return this.sodiumField;
			}
			set
			{
				this.sodiumField = value;
			}
		}

		/// <remarks/>
		public decimal magnesium
		{
			get
			{
				return this.magnesiumField;
			}
			set
			{
				this.magnesiumField = value;
			}
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[XmlTypeAttribute(Namespace = "urn:beerxml:water:v2")]
	public partial class WaterType : WaterBase
	{

		private decimal phField;

		private bool phFieldSpecified;

		private string notesField;

		/// <remarks/>
		public decimal pH
		{
			get
			{
				return this.phField;
			}
			set
			{
				this.phField = value;
			}
		}

		/// <remarks/>
		[XmlIgnoreAttribute()]
		public bool pHSpecified
		{
			get
			{
				return this.phFieldSpecified;
			}
			set
			{
				this.phFieldSpecified = value;
			}
		}

		/// <remarks/>
		public string notes
		{
			get
			{
				return this.notesField;
			}
			set
			{
				this.notesField = value;
			}
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[XmlTypeAttribute(Namespace = "urn:beerxml:mash:v2")]
	public partial class MashProcedureType
	{

		private string nameField;

		private TemperatureType grain_temperatureField;

		private TemperatureType sparge_temperatureField;

		private decimal phField;

		private bool phFieldSpecified;

		private string notesField;

		private MashStepType[] mash_stepsField;

		/// <remarks/>
		public string name
		{
			get
			{
				return this.nameField;
			}
			set
			{
				this.nameField = value;
			}
		}

		/// <remarks/>
		public TemperatureType grain_temperature
		{
			get
			{
				return this.grain_temperatureField;
			}
			set
			{
				this.grain_temperatureField = value;
			}
		}

		/// <remarks/>
		public TemperatureType sparge_temperature
		{
			get
			{
				return this.sparge_temperatureField;
			}
			set
			{
				this.sparge_temperatureField = value;
			}
		}

		/// <remarks/>
		public decimal pH
		{
			get
			{
				return this.phField;
			}
			set
			{
				this.phField = value;
			}
		}

		/// <remarks/>
		[XmlIgnoreAttribute()]
		public bool pHSpecified
		{
			get
			{
				return this.phFieldSpecified;
			}
			set
			{
				this.phFieldSpecified = value;
			}
		}

		/// <remarks/>
		public string notes
		{
			get
			{
				return this.notesField;
			}
			set
			{
				this.notesField = value;
			}
		}

		/// <remarks/>
		[XmlArrayItemAttribute("step", IsNullable = false)]
		public MashStepType[] mash_steps
		{
			get
			{
				return this.mash_stepsField;
			}
			set
			{
				this.mash_stepsField = value;
			}
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[XmlTypeAttribute(Namespace = "urn:beerxml:mash:step:v2")]
	public partial class MashStepType
	{

		private string nameField;

		private MashStepTypeType typeField;

		private VolumeType infuse_amountField;

		private TemperatureType step_temperatureField;

		private TimeType step_timeField;

		private TimeType ramp_timeField;

		private TemperatureType end_temperatureField;

		private string descriptionField;

		private decimal water_grain_ratioField;

		private bool water_grain_ratioFieldSpecified;

		private VolumeType decoction_amountField;

		private TemperatureType infuse_temperatureField;

		/// <remarks/>
		public string name
		{
			get
			{
				return this.nameField;
			}
			set
			{
				this.nameField = value;
			}
		}

		/// <remarks/>
		public MashStepTypeType type
		{
			get
			{
				return this.typeField;
			}
			set
			{
				this.typeField = value;
			}
		}

		/// <remarks/>
		public VolumeType infuse_amount
		{
			get
			{
				return this.infuse_amountField;
			}
			set
			{
				this.infuse_amountField = value;
			}
		}

		/// <remarks/>
		public TemperatureType step_temperature
		{
			get
			{
				return this.step_temperatureField;
			}
			set
			{
				this.step_temperatureField = value;
			}
		}

		/// <remarks/>
		public TimeType step_time
		{
			get
			{
				return this.step_timeField;
			}
			set
			{
				this.step_timeField = value;
			}
		}

		/// <remarks/>
		public TimeType ramp_time
		{
			get
			{
				return this.ramp_timeField;
			}
			set
			{
				this.ramp_timeField = value;
			}
		}

		/// <remarks/>
		public TemperatureType end_temperature
		{
			get
			{
				return this.end_temperatureField;
			}
			set
			{
				this.end_temperatureField = value;
			}
		}

		/// <remarks/>
		public string description
		{
			get
			{
				return this.descriptionField;
			}
			set
			{
				this.descriptionField = value;
			}
		}

		/// <remarks/>
		public decimal water_grain_ratio
		{
			get
			{
				return this.water_grain_ratioField;
			}
			set
			{
				this.water_grain_ratioField = value;
			}
		}

		/// <remarks/>
		[XmlIgnoreAttribute()]
		public bool water_grain_ratioSpecified
		{
			get
			{
				return this.water_grain_ratioFieldSpecified;
			}
			set
			{
				this.water_grain_ratioFieldSpecified = value;
			}
		}

		/// <remarks/>
		public VolumeType decoction_amount
		{
			get
			{
				return this.decoction_amountField;
			}
			set
			{
				this.decoction_amountField = value;
			}
		}

		/// <remarks/>
		public TemperatureType infuse_temperature
		{
			get
			{
				return this.infuse_temperatureField;
			}
			set
			{
				this.infuse_temperatureField = value;
			}
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
	[System.SerializableAttribute()]
	[XmlTypeAttribute(AnonymousType = true, Namespace = "urn:beerxml:mash:step:v2")]
	public enum MashStepTypeType
	{

		/// <remarks/>
		infusion,

		/// <remarks/>
		temperature,

		/// <remarks/>
		decoction,
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[XmlTypeAttribute(AnonymousType = true, Namespace = "urn:beerxml:recipe:v2")]
	public partial class RecipeTypeFermentation_stages
	{

		private FermentationStageType primaryField;

		private FermentationStageType secondaryField;

		private FermentationStageType tertiaryField;

		private FermentationStageType conditioningField;

		/// <remarks/>
		public FermentationStageType primary
		{
			get
			{
				return this.primaryField;
			}
			set
			{
				this.primaryField = value;
			}
		}

		/// <remarks/>
		public FermentationStageType secondary
		{
			get
			{
				return this.secondaryField;
			}
			set
			{
				this.secondaryField = value;
			}
		}

		/// <remarks/>
		public FermentationStageType tertiary
		{
			get
			{
				return this.tertiaryField;
			}
			set
			{
				this.tertiaryField = value;
			}
		}

		/// <remarks/>
		public FermentationStageType conditioning
		{
			get
			{
				return this.conditioningField;
			}
			set
			{
				this.conditioningField = value;
			}
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[XmlTypeAttribute(AnonymousType = true, Namespace = "urn:beerxml:recipe:v2")]
	public partial class RecipeTypeTaste
	{

		private string notesField;

		private decimal ratingField;

		/// <remarks/>
		public string notes
		{
			get
			{
				return this.notesField;
			}
			set
			{
				this.notesField = value;
			}
		}

		/// <remarks/>
		public decimal rating
		{
			get
			{
				return this.ratingField;
			}
			set
			{
				this.ratingField = value;
			}
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
	[System.SerializableAttribute()]
	[XmlTypeAttribute(Namespace = "urn:beerxml:unit:v2")]
	public enum QualitativeRangeType
	{

		/// <remarks/>
		[XmlEnumAttribute("very low")]
		verylow,

		/// <remarks/>
		low,

		/// <remarks/>
		[XmlEnumAttribute("medium low")]
		mediumlow,

		/// <remarks/>
		medium,

		/// <remarks/>
		[XmlEnumAttribute("medium high")]
		mediumhigh,

		/// <remarks/>
		high,

		/// <remarks/>
		[XmlEnumAttribute("very high")]
		veryhigh,
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[XmlTypeAttribute(AnonymousType = true, Namespace = "urn:beerxml:yeast:v2")]
	public partial class CultureInformationInventory
	{

		private VolumeType liquidField;

		private MassType dryField;

		private VolumeType slantField;

		private CultureInformationInventoryCulture cultureField;

		/// <remarks/>
		public VolumeType liquid
		{
			get
			{
				return this.liquidField;
			}
			set
			{
				this.liquidField = value;
			}
		}

		/// <remarks/>
		public MassType dry
		{
			get
			{
				return this.dryField;
			}
			set
			{
				this.dryField = value;
			}
		}

		/// <remarks/>
		public VolumeType slant
		{
			get
			{
				return this.slantField;
			}
			set
			{
				this.slantField = value;
			}
		}

		/// <remarks/>
		public CultureInformationInventoryCulture culture
		{
			get
			{
				return this.cultureField;
			}
			set
			{
				this.cultureField = value;
			}
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[XmlTypeAttribute(AnonymousType = true, Namespace = "urn:beerxml:yeast:v2")]
	public partial class CultureInformationInventoryCulture : VolumeType
	{

		private string dateField;

		/// <remarks/>
		[XmlAttributeAttribute()]
		public string date
		{
			get
			{
				return this.dateField;
			}
			set
			{
				this.dateField = value;
			}
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[XmlTypeAttribute(AnonymousType = true, Namespace = "urn:beerxml:v2")]
	public partial class beer_xmlFermentables
	{

		private FermentableType[] fermentableField;

		/// <remarks/>
		[XmlElementAttribute("fermentable")]
		public FermentableType[] fermentable
		{
			get
			{
				return this.fermentableField;
			}
			set
			{
				this.fermentableField = value;
			}
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[XmlTypeAttribute(AnonymousType = true, Namespace = "urn:beerxml:v2")]
	public partial class beer_xmlHop_varieties
	{

		private VarietyInformation[] hopField;

		/// <remarks/>
		[XmlElementAttribute("hop")]
		public VarietyInformation[] hop
		{
			get
			{
				return this.hopField;
			}
			set
			{
				this.hopField = value;
			}
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[XmlTypeAttribute(AnonymousType = true, Namespace = "urn:beerxml:v2")]
	public partial class beer_xmlMiscellaneous_ingredients
	{

		private MiscellaneousType[] miscellaneousField;

		/// <remarks/>
		[XmlElementAttribute("miscellaneous")]
		public MiscellaneousType[] miscellaneous
		{
			get
			{
				return this.miscellaneousField;
			}
			set
			{
				this.miscellaneousField = value;
			}
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[XmlTypeAttribute(AnonymousType = true, Namespace = "urn:beerxml:v2")]
	public partial class beer_xmlProcedure
	{

		private MashProcedureType[] mashField;

		/// <remarks/>
		[XmlElementAttribute("mash")]
		public MashProcedureType[] mash
		{
			get
			{
				return this.mashField;
			}
			set
			{
				this.mashField = value;
			}
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[XmlTypeAttribute(AnonymousType = true, Namespace = "urn:beerxml:v2")]
	public partial class beer_xmlProfiles
	{

		private WaterType[] waterField;

		/// <remarks/>
		[XmlElementAttribute("water")]
		public WaterType[] water
		{
			get
			{
				return this.waterField;
			}
			set
			{
				this.waterField = value;
			}
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[XmlTypeAttribute(AnonymousType = true, Namespace = "urn:beerxml:v2")]
	public partial class beer_xmlRecipes
	{

		private RecipeType[] recipeField;

		/// <remarks/>
		[XmlElementAttribute("recipe")]
		public RecipeType[] recipe
		{
			get
			{
				return this.recipeField;
			}
			set
			{
				this.recipeField = value;
			}
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[XmlTypeAttribute(AnonymousType = true, Namespace = "urn:beerxml:v2")]
	public partial class beer_xmlStyles
	{

		private StyleType[] styleField;

		/// <remarks/>
		[XmlElementAttribute("style")]
		public StyleType[] style
		{
			get
			{
				return this.styleField;
			}
			set
			{
				this.styleField = value;
			}
		}
	}

}
